trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  AZURE_SUBSCRIPTION: 'AzureServiceConnection'

stages:
- stage: CI
  jobs:
  - job: RunPipelineJob
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
    - script: |
        pip install azure-ai-ml
        az extension add -n ml -y
        az ml job create --file ci/pipeline.yml --resource-group $(resourceGroup) --workspace-name $(workspaceName)
      displayName: Submit Azure ML Pipeline Job

- stage: CD
  dependsOn: CI
  jobs:
  - job: DeployModel
    steps:
    - checkout: self
    - script: |
        az ml online-endpoint create --file cd/endpoint.yml --resource-group $(resourceGroup) --workspace-name $(workspaceName)
      displayName: Deploy Model to ACI
