$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: Pipeline job for training, evaluating, and registering a linear regression model
experiment_name: train-eval-register-pipeline
display_name: train-eval-register-pipeline
jobs:
  train_step:
    type: command
    component: ./ci/train_component.yml
    inputs:
      training_data: azureml:cars-dataset@1
    outputs:
      model_output:
        mode: upload
  eval_step:
    type: command
    component: ./ci/eval_component.yml
    inputs:
      model_input: ${{parent.jobs.train_step.outputs.model_output}}
  register_step:
    type: command
    component: ./ci/register_component.yml
    inputs:
      model_input: ${{parent.jobs.train_step.outputs.model_output}}
